part of Values;

class AppStrings {
  static const String appName = 'devAUF';
  static const String N = 'Nom';
  static const String Prof = 'Proffession';
  static const String A = 'Adresse';
  static const String loginTitle1 = "Authentification";
  static const String loginTitle2 = "Modification";
  static const String proffession = "Youtubeur";
  static const String Email = "Adresse Email :";
  static const String Mdp = "Mot De Passe :";
  static const String hinEmail = "Entrez votre adresse Email";
  static const String EE_valeur = "Veuillez entrer une valeur !";
  static const String EE_Invalid = "Email invalid !";
  static const String EE_Entrer = "Veuillez entrer un email valid";
  static const String EM_Entrer = "veuillez entrer une valeur !";
  static const String EM_Carac = "Veuillez entrer au moin 8 caractère !";
  static const String hinN = "Entrez votre Nom";
  static const String hinP = "Entrez votre Profession";
  static const String hinA = "Entrez votre Adresse";
  static const String Oublier = "Mot De Pass Oublié !";
  static const String connection = "Se connecter";
  static const String welcome = 'Détail Emission';
  static const String nom = 'Mamadou Alpha Barry';
  static const String adresse = 'Conakry, Lambanyi';
  static const String email = 'Barrymamadoualpha2003@gmail.com';
  static const String telephone = '+224625870245';
  static const String Exp = 'EXPÉRIENCE';
  static const String flu = 'Flutter';
  static const String ht = 'Html';
  static const String p = 'PHP';
  static const String contenue = 'Voir Plus';
  static const String Page = 'Detail Emission';
  static const String Page2 = 'Edition Profil';
  static const String Ed = 'Editer';
  static const String Det = 'Détail';
  static const String Emis = "Emission Streaming";
  static const String tape = "Tu m'as tapé";
  static const String Tchan1 = "Tu me manque";
  static const String Tchan2 = "La vie";
  static const String Tchan3 = "Ne n'oublie pas";
  static const String Achan1 = "Dadju";
  static const String Achan2 = "Soprano";
  static const String Achan3 = "Eminem";
}
